import type { Data } from 'plotly.js-dist-min'

// Static data files generated by `curation/airport_winds/convert_to_json.py`
export const AIRPORT_WINDS_DATA_PATH = '/data/airport-winds/'

export const DEFAULT_AIRPORT = 'PAFA'

export type WindSpeedUnits = 'kts' | 'mph' | 'm/s'
export type PetalCount = '8' | '16' | '36'

export interface AirportRunway {
  name: string
  heading: number
}

export interface AirportStation {
  sid: string
  label: string
  name: string
  lat: number
  lng: number
  startYear: number
  runways: AirportRunway[]
}

// Rose frequencies (%), indexed [speed range][direction], with directions
// running clockwise from north.
export type RoseFrequencies = number[][]

export interface AirportWindsData {
  sid: string
  // Keyed by petal count, then indexed by month (0 = all months).
  roses: Record<PetalCount, RoseFrequencies[]>
  // Percent calm, indexed by month (0 = all months).
  calms: number[]
  // Oldest available decade and 2010-2019, or null if insufficient data.
  comparison: {
    decades: string[]
    roses: Record<PetalCount, RoseFrequencies[]>
    calms: number[]
  } | null
  exceedance: {
    directions: number[]
    thresholds: {
      threshold: number
      rdcClass: string
      exceedance: number[]
    }[]
  }
  wep: {
    month: number[]
    year: number[]
    wep: number[]
  }
}

export const UNITS_LABELS: Record<WindSpeedUnits, string> = {
  kts: 'knots',
  mph: 'mph',
  'm/s': 'm/s',
}

export const PETAL_COUNT_LABELS: Record<PetalCount, string> = {
  '8': '8 (coarse)',
  '16': '16',
  '36': '36 (fine)',
}

// Gradient colors for speed ranges, from gentlest to strongest winds.
export const SPEED_COLORS = [
  '#d0d1e6',
  '#a6bddb',
  '#74a9cf',
  '#3690c0',
  '#0570b0',
  '#034e7b',
]

// Speed ranges are binned in mph, these are the equivalent labels.
// The lowest bound excludes calm (0) readings.
export const SPEED_RANGE_LABELS: Record<WindSpeedUnits, string[]> = {
  mph: ['0-6', '6-10', '10-14', '14-18', '18-22', '22+'],
  kts: ['0-5.2', '5.2-8.7', '8.7-12.2', '12.2-15.7', '15.7-19.1', '19.1+'],
  'm/s': ['0-2.7', '2.7-4.5', '4.5-6.3', '6.3-8', '8-9.8', '9.8+'],
}

// Allowable crosswind thresholds of 12.08, 14.96, and 18.41 mph.
export const THRESHOLD_LABELS: Record<WindSpeedUnits, string[]> = {
  mph: ['12.1 mph', '15 mph', '18.4 mph'],
  kts: ['10.5 kts', '13 kts', '16 kts'],
  'm/s': ['5.4 m/s', '6.7 m/s', '8.2 m/s'],
}

export const THRESHOLD_COLORS = ['#DC267F', '#FFB000', '#648FFF']

export const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
]

// Plotly's types don't cover all polar axis properties.
export const compassAxis: Record<string, any> = {
  rotation: 90,
  direction: 'clockwise',
  tickmode: 'array',
  tickvals: [0, 45, 90, 135, 180, 225, 270, 315],
  ticktext: ['N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW'],
  ticks: '',
  showline: false,
  color: '#888',
  gridcolor: '#efefef',
  tickfont: { color: '#444' },
}

export const radialAxis: Record<string, any> = {
  color: '#888',
  gridcolor: '#efefef',
  ticksuffix: '%',
  showticksuffix: 'last',
  showline: false,
  tickangle: 0,
  tickfont: { color: '#444' },
}

export const stationTitle = (station: AirportStation): string =>
  `${station.name} (${station.sid}), ${station.startYear}–present`

// Wind direction in degrees for each petal, clockwise from north.
const petalDirections = (petalCount: number): number[] =>
  Array.from({ length: petalCount }, (_, i) => (i * 360) / petalCount)

// One trace per speed range. Bars stack into petals by default. With
// `lines`, each speed range is drawn as a closed line instead, which is used
// to show differences between roses.
export const getRoseTraces = (
  rose: RoseFrequencies,
  units: WindSpeedUnits,
  options: { showLegend?: boolean; lines?: boolean; subplot?: string } = {}
): Data[] => {
  return rose.map((frequencies, i) => {
    const name = `${SPEED_RANGE_LABELS[units][i]} ${units}`
    const theta = petalDirections(frequencies.length)
    const trace: Record<string, any> = {
      r: [...frequencies],
      theta,
      name,
      marker: { color: SPEED_COLORS[i] },
      showlegend: options.showLegend ?? false,
      legendgroup: 'speed',
      hovertemplate: `%{r}% ${name} winds from %{theta}°<extra></extra>`,
      subplot: options.subplot ?? 'polar',
    }
    if (options.lines) {
      trace.type = 'scatterpolar'
      trace.mode = 'lines'
      trace.line = { color: SPEED_COLORS[i] }
      trace.r.push(frequencies[0])
      trace.theta = [...theta, theta[0]]
      trace.hovertemplate = `%{r:.2f}% change in ${name}<br>winds from %{theta}°<extra></extra>`
    } else {
      trace.type = 'barpolar'
    }
    return trace as Data
  })
}

// Maximum extent of any petal on the rose, summed across speed ranges.
export const maxPetal = (rose: RoseFrequencies): number => {
  return Math.max(
    ...rose[0].map((_, direction) =>
      rose.reduce((sum, speedRange) => sum + speedRange[direction], 0)
    )
  )
}

// Calm annotation text, with the "calm" label only if there's room for it.
export const calmText = (percent: number): string => {
  let text = Math.round(percent) + '%'
  if (percent > 20) {
    text += ' calm'
  }
  return text
}

export const purgeChart = (chartId: string) => {
  const { $Plotly } = useNuxtApp()
  try {
    const element = document.getElementById(chartId)
    if (element && element.hasChildNodes()) {
      $Plotly.purge(chartId)
    }
  } catch (error) {
    // Ignore purge errors - chart may already be cleaned up
    console.debug(`Chart purge skipped for ${chartId}:`, error)
  }
}
